# Generated by Django 5.1 on 2024-09-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcome',
            name='age',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
